language: node_js
node_js:
  - "10"
  - "11"
cache:
  directory:
    - $HOME/.yarn/bin
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn test
